import { asset } from "../assets";
import type { AudioManifest } from "../core/audio";
import type { SpriteSheetDefinition } from "../core/sprites";
import type { GameDefinition } from "../mechanics/stealth/model";

const playerSheet = (state: "idle" | "walk" | "interact", frames: number): SpriteSheetDefinition => ({
  src: asset(`assets/sprites/player/${state}.png`),
  frameWidth: 450,
  frameHeight: 556,
  frames,
  fps: 24,
  height: 159,
  anchorX: 0.3767,
  anchorY: 0.9694,
});

const watchmanSheet = (state: "idle" | "patrol" | "alert", frames: number): SpriteSheetDefinition => ({
  src: asset(`assets/sprites/watchman/${state}.png`),
  frameWidth: 381,
  frameHeight: 557,
  frames,
  fps: 24,
  height: 169,
  anchorX: 0.3714,
  anchorY: 0.9677,
});

const chiefSheet = (state: "idle" | "patrol" | "alert", frames: number): SpriteSheetDefinition => ({
  src: asset(`assets/sprites/chief/${state}.png`),
  frameWidth: 474,
  frameHeight: 561,
  frames,
  fps: 24,
  height: 185,
  anchorX: 0.3249,
  anchorY: 0.9643,
});

const sfx = (name: string, extension: "mp3" | "wav", volume: number) => ({
  src: asset(`assets/audio/sfx/${name}.${extension}`),
  volume,
});

const MARLINSPIKE_AUDIO: AudioManifest = {
  music: { src: asset("assets/audio/music.mp3"), volume: 0.18 },
  ambience: { src: asset("assets/audio/ambience.wav"), volume: 0.08 },
  secondaryLoop: { src: asset("assets/audio/radio.wav"), volume: 0.06 },
  voices: {
    root: asset("assets/audio/voices"),
    extension: "wav",
    volume: 0.78,
    duckedMusicVolume: 0.08,
  },
  sfx: {
    clue: sfx("clue", "wav", 0.38),
    hide: sfx("hide", "mp3", 0.22),
    suspicion: sfx("suspicion", "wav", 0.27),
    clear: sfx("clear", "wav", 0.18),
    detected: sfx("detected", "wav", 0.48),
    caught: sfx("caught", "wav", 0.32),
    lock: sfx("lock", "mp3", 0.36),
    open: sfx("open", "wav", 0.48),
    victory: sfx("victory", "mp3", 0.55),
    door: sfx("door", "wav", 0.34),
    turn: sfx("turn", "mp3", 0.16),
    "step-1": sfx("step-1", "mp3", 0.08),
    "step-2": sfx("step-2", "mp3", 0.08),
    "step-3": sfx("step-3", "mp3", 0.08),
    "step-4": sfx("step-4", "mp3", 0.08),
    "guard-step-1": sfx("guard-step-1", "mp3", 0.11),
    "guard-step-2": sfx("guard-step-2", "mp3", 0.11),
    "guard-step-3": sfx("guard-step-3", "mp3", 0.11),
    "guard-step-4": sfx("guard-step-4", "mp3", 0.11),
  },
};

const MARLINSPIKE_VOICE_BANKS = {
  clueCellar: [
    { id: "tintin_clue_cellar_01", text: "A torn page. The first piece of the dossier." },
  ],
  clueKitchen: [
    { id: "tintin_clue_kitchen_01", text: "Another piece—and hidden beside the pantry." },
  ],
  clueLibrary: [
    { id: "tintin_clue_library_01", text: "That's all three. Now for the attic strongbox." },
  ],
  hide: [
    { id: "tintin_hide_01", text: "Best wait until he turns." },
    { id: "tintin_hide_02", text: "From here, I can watch his timing." },
  ],
  retry: [
    { id: "tintin_retry_01", text: "The clues are safe. I'll try again." },
    { id: "tintin_retry_02", text: "I know his pattern now." },
  ],
  boxLocked: [
    { id: "tintin_box_locked_01", text: "The code is incomplete. I need all three pages." },
  ],
  victory: [
    {
      id: "tintin_victory_01",
      text: "The ledger and landing chart—proof at last. This plot will be exposed before the ship comes in.",
    },
  ],
  watchmanIdle: [
    { id: "watchman_idle_01", text: "Chief wants the house quiet until dawn." },
    { id: "watchman_idle_02", text: "Doors watched. Corridors clear." },
  ],
  watchmanSuspicion: [
    { id: "watchman_suspicion_01", text: "Hold on… someone there?" },
    { id: "watchman_suspicion_02", text: "What was that?" },
  ],
  watchmanSpotted: [
    { id: "watchman_spotted_01", text: "You there—stand still!" },
    { id: "watchman_spotted_02", text: "Stop! You're not allowed up here." },
    { id: "watchman_spotted_03", text: "An intruder! Away from that door." },
  ],
  watchmanEscort: [
    { id: "watchman_escort_01", text: "Back to the door with you." },
    { id: "watchman_escort_02", text: "That's far enough. Back you go." },
  ],
  chiefIntro: [
    { id: "chief_intro_01", text: "Signal before dawn. The ledger stays in the box." },
  ],
  chiefIdle: [
    { id: "chief_idle_01", text: "No mistakes tonight." },
    { id: "chief_idle_02", text: "Once the signal goes out, the coast is clear." },
  ],
  chiefSuspicion: [
    { id: "chief_suspicion_01", text: "Who's there?" },
    { id: "chief_suspicion_02", text: "I heard something by the console." },
  ],
  chiefSpotted: [
    { id: "chief_spotted_01", text: "You! Away from that strongbox!" },
    { id: "chief_spotted_02", text: "The reporter. Stop him!" },
  ],
  chiefEscort: [
    { id: "chief_escort_01", text: "Back downstairs. You saw nothing." },
  ],
} as const;

export const marlinspikeGame: GameDefinition = {
  id: "marlinspike-manor",
  mode: "stealth",
  presentation: {
    themeClass: "theme-marlinspike",
    aspectRatio: 16 / 9,
    maxStageWidth: 1000,
  },
  assets: {
    titleArt: asset("assets/title-art.png"),
    world: asset("assets/manor.png"),
    portrait: asset("assets/tintin-portrait.png"),
    clue: asset("assets/props/clue-page.png"),
    finalObjective: {
      locked: asset("assets/props/strongbox.png"),
      opening: [
        asset("assets/props/strongbox-open-1.png"),
        asset("assets/props/strongbox-open-2.png"),
        asset("assets/props/strongbox-open-3.png"),
      ],
    },
    characters: {
      player: {
        idle: playerSheet("idle", 34),
        walk: playerSheet("walk", 20),
        interact: playerSheet("interact", 1),
      },
      watchman: {
        idle: watchmanSheet("idle", 30),
        patrol: watchmanSheet("patrol", 21),
        alert: watchmanSheet("alert", 1),
      },
      chief: {
        idle: chiefSheet("idle", 60),
        patrol: chiefSheet("patrol", 34),
        alert: chiefSheet("alert", 1),
      },
    },
    audio: MARLINSPIKE_AUDIO,
  },
  copy: {
    playerName: "Tintin",
    guardNames: { watchman: "Watchman", chief: "Syndicate chief" },
    locationName: "Marlinspike Manor",
    clockLabel: "Before dawn",
    caseLabel: "CONFIDENTIAL · CASE 47",
    titleEyebrow: "A five-floor stealth mystery",
    title: "Infiltrate the manor before dawn.",
    titleSummary:
      "Recover three torn clue pages, read the watchmen’s patrols, and reach the attic strongbox before the smuggling ship arrives.",
    titleRules: ["Stay out of sight", "Collect all 3 clues", "Unlock the strongbox"],
    startLabel: "Begin investigation",
    openingLine: "The manor is occupied. Quietly now—there must be proof inside.",
    pauseTitle: "The manor waits.",
    pauseBody: "You’re safe here. Your clues and floor progress have been kept.",
    helpTitle: "How to slip through the manor",
    finalObjectiveName: "strongbox",
    finalActionLabel: "Open strongbox",
    finalReadyHint: "Use the three-page cipher",
    finalLockedHint: "The lock needs {count} clues",
    victoryEyebrow: "Case closed · Before dawn",
    victoryTitle: "The plot is exposed.",
    victoryBody:
      "The torn pages match the syndicate ledger. With the landing chart secured, the smugglers’ midnight operation will make tomorrow’s front page.",
    victoryWorldLabel: "Manor cleared",
    credits: "A browser stealth mystery · Best played with sound",
  },
  intro: {
    establishingMs: 900,
    skipLabel: "Skip briefing",
    beats: [
      {
        id: "destination",
        floor: 5,
        kicker: "The destination",
        title: "The attic strongbox",
        description: "The syndicate ledger is locked at the top of the manor.",
        focus: { x: 50.8, y: 16.2, zoom: 2.65 },
        marker: "final-objective",
        durationMs: 2850,
      },
      {
        id: "library",
        floor: 4,
        kicker: "Floor IV",
        title: "The final cipher page",
        description: "A moving patrol guards the maritime library.",
        focus: { x: 78.1, y: 41.6, zoom: 2.35 },
        marker: "clue",
        durationMs: 2650,
      },
      {
        id: "gallery",
        floor: 3,
        kicker: "Floor III",
        title: "Crossed sightlines",
        description: "Two watchmen turn the portrait gallery into a timing puzzle.",
        focus: { x: 50, y: 54, zoom: 2.12 },
        durationMs: 2650,
      },
      {
        id: "kitchen",
        floor: 2,
        kicker: "Floor II",
        title: "The pantry lookout",
        description: "A torn page waits beyond the guard’s gaze.",
        focus: { x: 84.8, y: 79, zoom: 2.35 },
        marker: "clue",
        durationMs: 2650,
      },
      {
        id: "cellar",
        floor: 1,
        kicker: "Floor I",
        title: "The first piece",
        description: "The trail begins with a clue in the wine cellar.",
        focus: { x: 38.3, y: 97, zoom: 2.5 },
        marker: "clue",
        durationMs: 2500,
      },
      {
        id: "start",
        floor: 1,
        kicker: "Your way in",
        title: "Begin at the cellar door",
        description: "Move quietly. Learn their patterns. Keep every clue.",
        focus: { x: 10.5, y: 91.2, zoom: 2.35 },
        showPlayer: true,
        durationMs: 2200,
      },
      {
        id: "pullback",
        floor: 1,
        kicker: "",
        title: "",
        description: "",
        focus: { x: 50, y: 50, zoom: 1 },
        showPlayer: true,
        showCaption: false,
        showInRoute: false,
        settleToGameplay: true,
        cameraDurationMs: 2700,
        durationMs: 3050,
      },
    ],
  },
  mechanics: {
    maxHearts: 3,
    playerSpeed: 148,
    playerBounds: { min: 72, max: 928 },
    doorThresholds: { left: 158, right: 842 },
    safeDoorZones: { left: 145, right: 855 },
    suspicionDrainPerSecond: 1.55,
    assistAfterFailures: 2,
    adaptivePauseBonus: 1,
  },
  world: {
    floorOrder: [1, 2, 3, 4, 5],
    floors: {
      1: {
        name: "Wine Cellar",
        roman: "I",
        eyebrow: "Floor I · A quiet beginning",
        groundY: 978,
        spawns: { left: 105, right: 860 },
        objective: "Recover the torn page, then use the right-hand door.",
        tip: "Move with A / D or the arrow keys. Press E near a clue or door.",
        band: { top: 80.8, bottom: 100 },
        covers: [],
        guards: [],
      },
      2: {
        name: "Kitchen & Pantry",
        roman: "II",
        eyebrow: "Floor II · The lookout",
        groundY: 808,
        spawns: { left: 130, right: 870 },
        objective: "Take the pantry page and reach the left-hand door unseen.",
        tip: "Watch the lookout's gaze. Stand still in the pantry nook to hide.",
        band: { top: 62.8, bottom: 80.8 },
        covers: [{ from: 704, to: 812, label: "Pantry nook" }],
        guards: [
          {
            id: "kitchen-lookout",
            kind: "watchman",
            x: 550,
            facing: "left",
            motion: "stationary",
            range: 190,
            turnInterval: 4,
            detectionWindup: 1.35,
          },
        ],
      },
      3: {
        name: "Portrait Gallery",
        roman: "III",
        eyebrow: "Floor III · Crossed sightlines",
        groundY: 631,
        spawns: { left: 120, right: 870 },
        objective: "Cross the gallery and reach the right-hand door.",
        tip: "Use the vase and armour niches as safe waiting points.",
        band: { top: 43.7, bottom: 62.8 },
        covers: [
          { from: 299, to: 343, label: "Vase niche" },
          { from: 375, to: 429, label: "Armour niche" },
        ],
        guards: [
          {
            id: "gallery-left",
            kind: "watchman",
            x: 174,
            facing: "right",
            motion: "stationary",
            range: 330,
            turnInterval: 5,
            detectionWindup: 1.3,
          },
          {
            id: "gallery-right",
            kind: "watchman",
            x: 770,
            facing: "left",
            motion: "stationary",
            range: 310,
            initialTimer: 2.5,
            turnInterval: 5,
            detectionWindup: 1.3,
          },
        ],
      },
      4: {
        name: "Maritime Library",
        roman: "IV",
        eyebrow: "Floor IV · The patrol",
        groundY: 434,
        spawns: { left: 130, right: 870 },
        objective: "Secure the final page, then slip through the left-hand door.",
        tip: "Follow behind the patrol. Hide in the reading alcove before he turns.",
        band: { top: 24.2, bottom: 43.7 },
        covers: [{ from: 611, to: 728, label: "Reading alcove" }],
        guards: [
          {
            id: "library-patrol",
            kind: "watchman",
            x: 760,
            facing: "left",
            motion: "patrol",
            range: 235,
            detectionWindup: 0.95,
            patrol: { min: 220, max: 760, speed: 88, pause: 2 },
          },
        ],
      },
      5: {
        name: "Attic Radio Room",
        roman: "V",
        eyebrow: "Floor V · The strongbox",
        groundY: 238,
        spawns: { left: 128, right: 840 },
        objective: "Reach the strongbox with all three pages and expose the plot.",
        tip: "Wait by the door, then move when the chief paces to the right.",
        band: { top: 0, bottom: 24.2 },
        covers: [],
        guards: [
          {
            id: "syndicate-chief",
            kind: "chief",
            x: 600,
            facing: "left",
            motion: "patrol",
            range: 360,
            detectionWindup: 1.02,
            patrol: { min: 540, max: 660, speed: 66, pause: 3 },
          },
        ],
        onEnterVoice: { bank: "chiefIntro", speaker: "Syndicate chief", textTone: "warning" },
      },
    },
    clues: {
      cellar: { floor: 1, x: 383, y: 970, voiceBank: "clueCellar" },
      kitchen: { floor: 2, x: 848, y: 790, voiceBank: "clueKitchen" },
      library: { floor: 4, x: 781, y: 416, voiceBank: "clueLibrary" },
    },
    floorClues: { 1: "cellar", 2: "kitchen", 4: "library" },
    requiredClues: { 1: "cellar", 2: "kitchen", 4: "library" },
    navigation: {
      "1-right": { floor: 2, side: "right" },
      "2-right": { floor: 1, side: "right" },
      "2-left": { floor: 3, side: "left" },
      "3-left": { floor: 2, side: "left" },
      "3-right": { floor: 4, side: "right" },
      "4-right": { floor: 3, side: "right" },
      "4-left": { floor: 5, side: "left" },
      "5-left": { floor: 4, side: "left" },
    },
    finalObjective: { floor: 5, x: 508, interactionRange: 72 },
  },
  voices: {
    banks: MARLINSPIKE_VOICE_BANKS,
    hide: "hide",
    retry: "retry",
    finalLocked: "boxLocked",
    victory: "victory",
    guard: {
      watchman: {
        idle: "watchmanIdle",
        suspicion: "watchmanSuspicion",
        spotted: "watchmanSpotted",
        escort: "watchmanEscort",
      },
      chief: {
        idle: "chiefIdle",
        suspicion: "chiefSuspicion",
        spotted: "chiefSpotted",
        escort: "chiefEscort",
      },
    },
  },
};
